
version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:jdk11
    user: 1000:1000
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
