
version: "3"
services:
  jenkins:
    image: jenkins/jenkins:jdk11
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins_home: