pipeline {
    agent any
    // {

        // docker {
        //     image 'node:lts-buster-slim'
        //     args '-p 3000:3000'
        // }
    // }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Testing..."'
                sh 'npm install --save-dev cross-env'
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo "Delivering..."'
                
                script {
                    def myEnv = docker.build('myWebApp:snapshot')
                    myEnv.inside {
                        sh 'npm run build'
                    }
                }
            }
        }
    }
}